# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "lb01" do |lb01|
    lb01.vm.box = "ubuntu/bionic64"
    lb01.vm.hostname = "lb01"
    lb01.vm.network :private_network, ip: "10.11.12.50"
  end

  config.vm.define "Master" do |Master|
    Master.vm.box = "ubuntu/bionic64"
    Master.vm.hostname = "Master"
    Master.vm.network :private_network, ip: "10.11.12.51"
  end

  config.vm.define "Slave" do |Slave|
    Slave.vm.box = "ubuntu/bionic64"
    Slave.vm.hostname = "Slave"
    Slave.vm.network :private_network, ip: "10.11.12.52"
  end
end
