# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "Master" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.hostname = "Master"
    web01.vm.network :private_network, ip: "10.11.12.51"
    web01.vm.provision "shell", path: "replication1.sh"
  end

  config.vm.define "Slave" do |web02|
    web02.vm.box = "ubuntu/bionic64"
    web02.vm.hostname = "Slave"
    web02.vm.network :private_network, ip: "10.11.12.52"
    web02.vm.provision "shell", path: "replication2.sh"
  end
end
